var events={
	"anniversary":{
		"name":"Ten Years of Adventure Land",
		"modal":"event-anniversary",
		"sprite":"sixcake",
		"announcement":{"title":"10 Years of Adventure","color":"#F0B742","accent":"#ED86AB","effect":"confetti","text":"Find players for cake and Gifts."},
		"type":"seasonal",
	},
	"abtesting":{
		"name":"A/B Testing",
		"modal":"event-abtesting",
		"sprite":"thehelmet",
		"announcement":{"color":"#EC526D","accent":"#78D6A0","effect":"sparks","text":"Join the team battle."},
		"duration":8*60,
		"join":true,
		"type":"daily",
	},
	"goobrawl":{
		"name":"Goo Brawl",
		"modal":"event-goobrawl",
		"sprite":"rgoo",
		"announcement":{"color":"#F78159","accent":"#A5DC6C","effect":"bubbles","text":"Join the goo fight."},
		"duration":9*60,
		"join":true,
		"type":"daily",
	},
	"crabxx":{
		"name":"Giga Crab",
		"modal":"event-crabxx",
		"sprite":"crabxx",
		"announcement":{"color":"#F18B64","accent":"#73D5DB","effect":"splash","text":"Help take down Giga Crab."},
		"duration":60*40,
		"join":true,
		"type":"daily",
	},
	"franky":{
		"name":"Franky",
		"modal":"event-franky",
		"sprite":"franky",
		"announcement":{"color":"#9FCF6D","accent":"#C29BE7","effect":"sparks","text":"Franky is awake."},
		"duration":60*40,
		"join":true,
		"type":"nightly",
	},
	"icegolem":{
		"name":"Ice Golem",
		"modal":"event-icegolem",
		"sprite":"icegolem",
		"announcement":{"color":"#8BD4F4","accent":"#E0F6FF","effect":"snow","text":"Face the Ice Golem."},
		"duration":60*40,
		"join":true,
		"type":"nightly",
	},
	"holidayseason":{
		"name":"Holiday Season",
		"modal":"event-holidayseason",
		"sprite":"grinch",
		"announcement":{"color":"#7ACA8B","accent":"#EE8B92","effect":"snow","text":"Collect candy canes and gifts."},
		"duration":60*60*24*30,
		//"join":true,
		"type":"seasonal",
	},
	"lunarnewyear":{
		"name":"Lunar New Year",
		"modal":"event-lunarnewyear",
		"sprite":"redenvelopev4",
		"announcement":{"color":"#EF7272","accent":"#F3D16E","effect":"fireworks","text":"Envelopes are dropping across the land."},
		"duration":60*60*24*15,
		//"join":true,
		"type":"seasonal",
	},
	"valentines":{
		"name":"Valentines",
		"modal":"event-valentines",
		"sprite":"cupid",
		"announcement":{"color":"#F08AB6","accent":"#F5C8D9","effect":"hearts","text":"Candy Pops and Love Goo await."},
		"duration":60*60*24*10,
		//"join":true,
		"type":"seasonal",
	},
	"egghunt":{
		"name":"Egg Hunt",
		"modal":"event-egghunt",
		"sprite":"basketofeggs",
		"announcement":{"color":"#AFD778","accent":"#D7A1E8","effect":"confetti","text":"Hunt for eggs across the land."},
		"duration":60*60*24*15,
		//"join":true,
		"type":"seasonal",
	},
	"halloween":{
		"name":"Halloween",
		"modal":"event-halloween",
		"sprite":"candy0",
		"announcement":{"color":"#F5A05B","accent":"#AD91DC","effect":"embers","text":"Collect candy from monsters."},
		"duration":60*60*24*30,
		//"join":true,
		"type":"seasonal",
	},
};
